### ISSUE TITLE
I would like to be warned before

### ISSUE THREAD

**Issue by eramdam** [rodrigopolo/EvenBetterTweetDeck#2]
Look, I'm okay with the existence of this fork, it's the principle of open source, right? But I'm not okay with three things:

- The name very very similar of the extension
- the exact same screenshots being used. I feel like it gives a weird feeling of a scammy/counterfeit practice
- I would love to have known this before

Plus it appears that the official Twitter emojis supports the new additions of emoji so I am not opposed anymore to merge this in the main project :)

**Comment by rodrigopolo** [comment]
To be completely honest, I cloned your git repo and made the changes, then I told you and my friends about the additions I did, as you have stated, you wouldn’t add the new additions because the emojis used are from Apple and not the ones that Twitter use, and that’s fine.

But later on, some of my friends ask me to publish my additions, first thing I did was to pack the extension as a CRX using Chrome and share it with them, but some friends told me they didn’t understand how to install the extension, so after some requests I decided to publish the extension, it is the first and only extension I have published and I expended some money to do so hahahahaha, my goal was to share my improvements to the extension, never to steal or take credit, in the extension page is very clearly stated that is a fork from your work and all credit goes to you, the only thing I added was the new emojis and the replacement function which at the time needed the new emojis in order to display the all new emojis, I almost didn’t change the screenshots but I finally did to show the new emojis and I can’t publish the extension using the very same name you use, I though it wasn’t fair to use a completely different name, the closest thing I found to be fair first with your work and then for the additions was to add something different to the name using almost the same name.

It took more than two months for Twemoji to publish the new emojis and for Twitter to implement the new emojis, and having the new Apple emojis was my motivations, being able to see the emojis, if someone had done the new emojis aditions before, I had not had the need to do this repository.

So, in an honest good faith I published this fork under some friends request, now that Twemoji has finally added the new emojis I’ll add them and push a pull request to you as soon as I can, I’m even thinking on adding an option to choose which emoji version to use, having Apple, Emoji One and Twemoji as options. Again, there was no malicious or bad intention behind publishing the enhanced extension, just sharing the possibility to type and see the latest emojis.

**Comment by eramdam** [comment]
I know it's was out of good intentions, no worries, it's just that the screenshots could be (imo) somehow misleading. Even I get sometimes general support about TweetDeck itself, so imagine the potential confusion that you could get :p  

I like the idea of choosing multiples styles of emoji as well ! I just advise you not to spend too long on this since I'm going to rewrite BTD in a v3 during 2016

**Comment by eramdam** [comment]
@rodrigopolo Can you unpublish the extension from the Store? It doesn't have been updated for almost 2 years and some users are confusing it with the "real" Better TweetDeck.

**Comment by rodrigopolo** [comment]
It is unpublished right now.

**Comment by eramdam** [comment]
@rodrigopolo awesome, thanks!
